### ISSUE TITLE
Rgraphviz 2.57.1 compilation error on Linux Ubuntu 24.04.4 LTS

### ISSUE THREAD

**Issue by hpages** [kasperdanielhansen/Rgraphviz#28]
**Rgraphviz** 2.57.1 fails to compile on Linux Ubuntu 24.04.4 LTS. See: https://bioconductor.org/checkResults/3.24/bioc-LATEST/Rgraphviz/nebbiolo2-install.html

FWIW I get the same error on my Ubuntu 24.04.4 LTS laptop with R 4.6.1 + BioC 3.24.

IMPORTANT NOTE: This compilation error seems to happen only when running `R CMD check` on the package _source tree_. Running it on the package _source tarball_ works fine. 

@jeroen: The [R Universe builds](https://bioc.r-universe.dev/Rgraphviz#checktable) don't seem to report this error. Maybe because they run `R CMD INSTALL` on the _source tarball_?

Thanks,
H.

**Comment by jeroen** [comment]
Yes indeed, R-universe first creates a source tarball from the git checkout, and runs CMD check on that same tarball on each platform.

**Comment by kasperdanielhansen** [comment]
Thanks for looking into this and huge thanks to @jeroen for the PR. The PR contains an analysis of the problem. But in short, Rgraphviz bundles graphviz and this tool needs to be compiled, so during installation, Rgraphviz (roughly) does
```
cd src/graphviz
./configure
make install
```
(pseudocode, arguments left out). (R)Graphviz uses autotools for configuration etc. Now, a github checkout seems to occasionally cause problems with the timestamps on the file, leading to make thinking that autotools needs to re-run autotools. These days, this happens automatically because autotools has changed to using "maintainer mode" per default. See for example https://flameeyes.blog/2008/06/13/maintaner-mode/. There are at least 2 solutions to this, one is implemented in the PR:

1) run touch on all relevant files, so the time stamps are fixed.
2) disable maintainer mode which can either be done by using the autotools command `AM_MAINTAINER_MODE([disable])` or by using the command line flag as `make --disable-maintainer-mode`

So @jeroen choose 1), but to me at least, the most direct solution is 2)? Any comments on this choice? This is all rather new to me, so my analysis might very well be faulty.

For the broader project, it seems like packages using autotools should always disable maintainer mode. This is more a note to @hpages and the rest of the core team.

Finally, @hpages, looking at the build reports, R CMD check is run on a tarball, but R CMD INSTALL is run on the source directory. I see why it is sensible that R CMD INSTALL is run on source in case R CMD build fails. What I don't understand in this case is how the tarball passed to R CMD check is being produced? If INSTALL fails, how is the tarball made?

**Comment by jeroen** [comment]
> What I don't understand in this case is how the tarball passed to R CMD check is being produced? If INSTALL fails, how is the tarball made?

When `R CMD build` fails, R-universe falls back to `R CMD build --no-build-vignettes` which does not require any installation.

**Comment by kasperdanielhansen** [comment]
Any comment on disabling maintainer mode (which seems the "right" solution to me) vs. your choice of using "touch"? Indifference?

**Comment by jeroen** [comment]
I have no opinion on this. In my own packages I avoid using autotools at all cost. To me it is usually redundant and adds a lot of bloat and complexity and ambiguity to the build process, as we see in this issue.

I prefer a single Makevars file in which we hardcode the configuration of the R package, without making autotools guess al the things.

**Comment by hpages** [comment]
@kasperdanielhansen 

> If INSTALL fails, how is the tarball made?

On our build machines, the tarball is  produced with `R CMD build` (the BUILD step). For some reasons, on the Linux build machine, the BUILD step is succesful even though the INSTALL step (`R CMD INSTALL`) fails. This is a very rare situation that I've only seen a couple of times on our daily report in the last 15 years 😉 IIUC `R CMD build` makes a copy of the package source tree to a temporary location and then runs `R CMD INSTALL` on the copy. My guess is that the copy has the effect of updating all the timestamps hence why it works.

@jereon

> When `R CMD build` fails, R-universe falls back to `R CMD build --no-build-vignettes` which does not require any installation.

FWIW some packages have R code in an `\Sexp{}` (or something like that) in their man pages, in which case `R CMD build --no-build-vignettes` will try to install them in order to be able to evaluate the code. IIRC we used to have a few packages like this in Bioconductor. Used to be a handful or something like that. Don't know how many we still have today, if any.

**Comment by kasperdanielhansen** [comment]
A further analysis of this issue, building on @jeroen's excellent analysis in his pull request.

Current Rgraphviz, which bundles graphviz 2.28 does not support disabling the maintainer flag (which is IMO the "correct" solution to this issue). I have tried to add the `AM_MAINTAINER_MODE` to `src/graphviz/configure.ac` and run `autoreconf -ivf` but found that the various `configure.ac` bundled with Graphviz 2.28 had many errors due to changes in autotools (Graphviz 2.28 is from 2011).

I have checked Graphviz 16 (released in the last week or so) and this version handles this issue correctly in the sense that maintainer mode is disabled. This adds to the pressure to update the bundled Graphviz inside Rgraphviz; one could also hope that many of the warnings emitted by Rgraphviz on various platforms would be fixed. I have started to look into this, but there has been some changes to the internal structure of Graphviz. Back in 2011, I ripped out the graph layout routines and discarded the code for rendering graphs as rendering is done in R and has a lot of unneeded dependencies. I would have to re-analyze Graphviz and essentially redo this old work. But this should be possible with some help from AI. Finally, because Rtools for windows now has more stuff bundled, it is probably possible to compile Graphviz 16 from source inside the R for Windows build system, so I could discard the various binaries files that is shipped with Rgraphviz. 

For now, I have merged @jeroen PR which should fix the issue for now, and then I will try to update Graphviz in the next month or two. I am still a bit hesitant to do this, because it was such a huge lift when I last did it in 2011. Especially testing and debugging on Windows was hard for me. Hopefully, this will be easier in 2026.
